"""Added audio features

Revision ID: 07aa3e0512df
Revises: 9a2710acc810
Create Date: 2020-06-06 12:10:38.336277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07aa3e0512df'
down_revision = '9a2710acc810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('acousticness', sa.Integer(), nullable=True))
    op.add_column('songs', sa.Column('danceability', sa.Integer(), nullable=True))
    op.add_column('songs', sa.Column('energy', sa.Integer(), nullable=True))
    op.add_column('songs', sa.Column('instrumentalness', sa.Integer(), nullable=True))
    op.add_column('songs', sa.Column('liveness', sa.Integer(), nullable=True))
    op.add_column('songs', sa.Column('speechiness', sa.Integer(), nullable=True))
    op.add_column('songs', sa.Column('valence', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'valence')
    op.drop_column('songs', 'speechiness')
    op.drop_column('songs', 'liveness')
    op.drop_column('songs', 'instrumentalness')
    op.drop_column('songs', 'energy')
    op.drop_column('songs', 'danceability')
    op.drop_column('songs', 'acousticness')
    # ### end Alembic commands ###
