"""Caching for playlists

Revision ID: 2980293e7e01
Revises: 
Create Date: 2020-05-29 08:17:48.768177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2980293e7e01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_playlists', sa.String(length=10000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_playlists')
    # ### end Alembic commands ###
