"""More track informations

Revision ID: 6e1737f5f49b
Revises: e66096b5ad8b
Create Date: 2020-06-15 16:39:44.687961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e1737f5f49b'
down_revision = 'e66096b5ad8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('explicit', sa.Boolean(), nullable=True))
    op.add_column('songs', sa.Column('length', sa.Integer(), nullable=True))
    op.add_column('songs', sa.Column('markets', sa.Integer(), nullable=True))
    op.add_column('songs', sa.Column('popularity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'popularity')
    op.drop_column('songs', 'markets')
    op.drop_column('songs', 'length')
    op.drop_column('songs', 'explicit')
    # ### end Alembic commands ###
