"""added refresh token

Revision ID: 71968e7b3f88
Revises: 6e1737f5f49b
Create Date: 2020-06-19 12:19:07.694013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71968e7b3f88'
down_revision = '6e1737f5f49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
