"""Added album info

Revision ID: d0c330f867f1
Revises: 71968e7b3f88
Create Date: 2020-06-19 18:36:23.945361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c330f867f1'
down_revision = '71968e7b3f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('album_markets', sa.Integer(), nullable=True))
    op.add_column('songs', sa.Column('album_popularity', sa.Integer(), nullable=True))
    op.add_column('songs', sa.Column('album_release', sa.Integer(), nullable=True))
    op.add_column('songs', sa.Column('album_tracks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'album_tracks')
    op.drop_column('songs', 'album_release')
    op.drop_column('songs', 'album_popularity')
    op.drop_column('songs', 'album_markets')
    # ### end Alembic commands ###
