"""fixed migration

Revision ID: e66096b5ad8b
Revises: 07aa3e0512df
Create Date: 2020-06-06 12:21:32.625246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66096b5ad8b'
down_revision = '07aa3e0512df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('loudness_graph', sa.String(length=50000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'loudness_graph')
    # ### end Alembic commands ###
