name: Test app

on:
  push:
    branches:
      - master

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1"
      - run: |
          go mod download
          go test -v ./...
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          GENIUS_TOKEN: ${{ secrets.GENIUS_TOKEN }}
          USER_REFRESH_TOKEN: ${{ secrets.USER_REFRESH_TOKEN }}
