name: Test app

on:
  push:
    branches:
      - master

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1"
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download dependencies
        run: |
          go mod download
      - name: Test the app
        run: |
          go test -v ./...
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          GENIUS_TOKEN: ${{ secrets.GENIUS_TOKEN }}
          USER_REFRESH_TOKEN: ${{ secrets.USER_REFRESH_TOKEN }}
